---
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
  - cron: 46 0 * * *
jobs:
  scrape:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch latest data
      env:
        TRIPIT_CLIENT_TOKEN: ${{ secrets.TRIPIT_CLIENT_TOKEN }}
        TRIPIT_CLIENT_TOKEN_SECRET: ${{ secrets.TRIPIT_CLIENT_TOKEN_SECRET }}
        TRIPIT_ACCESS_TOKEN: ${{ secrets.TRIPIT_ACCESS_TOKEN }}
        TRIPIT_ACCESS_TOKEN_SECRET: ${{ secrets.TRIPIT_ACCESS_TOKEN_SECRET }}
      run: |-
        tripit-api-to-json | jq . > tripit.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
  release-docker-build:
    name: Release Docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      id: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Check for CRLF endings
      id: crlf-lint
      uses: erclu/check-crlf@v1
    - name: Setup Python
      id: python-setup
      uses: actions/setup-python@v1
    - name: Lint Python
      id: python-lint
      uses: whynothugo/python-linting@master
    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v1
      with:
        strict: true
    - name: Bump Version
      id: github-tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Prepare Environment
      id: prepare
      env:
        DOCKER_IMAGE: ${{ github.repository }}
        DOCKER_PLATFORMS: linux/amd64
        VERSION: ${{ steps.github-tag.outputs.tag }}
      run: |
        TAGS="--tag ${DOCKER_IMAGE,,}:${VERSION} --tag ${DOCKER_IMAGE,,}:latest"
        echo ::set-output name=docker_image::${DOCKER_IMAGE,,}
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
          --build-arg VERSION=${VERSION} \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=${GITHUB_SHA::8} \
          ${TAGS} --file ./Dockerfile ./
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Layer Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build Images
      run: |
        docker buildx build \
          --output "type=image,push=false" \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          ${{ steps.prepare.outputs.buildx_args }}
    - name: Docker Login
      if: success()
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Push Images
      if: success()
      run: |
        docker buildx build \
          --output "type=image,push=true" \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          ${{ steps.prepare.outputs.buildx_args }}
    - name: Sync readme and description from GitHub to Docker Hub
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_USERNAME }}
        pass: ${{ secrets.DOCKER_PASSWORD }}
    - name: Clear
      run: |
        rm -f ${HOME}/.docker/config.json
